### ISSUE TITLE
Allow the download url to be set

### ISSUE THREAD

**Issue by GentlemanHal** [build-canaries/nevergreen-docker#3]
Currently it just downloads the latest which makes it impossible to install a specific version.

I'm not exactly sure how Docker works, but if it's possible users should be able to set or pass in the url to download from allowing any version to be downloaded.

**Comment by manasik** [comment]
will sort this out now

**Comment by GentlemanHal** [comment]
@manasik any update on this? 

No worries if you don't have the time, but perhaps you could briefly outline the changes here? Is the correct way to just use environment variable?

**Comment by manasik** [comment]
sorry @GentlemanHal. Will definitely invest some time this weekend. I do have a plan. So happy to elaborate the same over the weekend too.
