### ISSUE TITLE
By default this runs as root - can we create a new user that can be used to run

### ISSUE THREAD

**Issue by robhorn-thoughtworks** [build-canaries/nevergreen-docker#5]
Running this on openshift managed by RedHat it is not possible to run a docker container as root.  A new user needs to be added in order to then user the -u option in the docker run command.

could be something like:
```
FROM ubuntu:14.04

RUN apt-get update

# Replace 1000 with your user / group id
RUN export uid=1000 gid=1000 && \
    mkdir -p /home/abc && \
    echo "abc:x:${uid}:${gid}:Abc,,,:/home/abc:/bin/bash" >> /etc/passwd && \
    echo "abc:x:${uid}:" >> /etc/group && \
    echo "abc ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/abc && \
    chmod 0440 /etc/sudoers.d/abc && \
    chown ${uid}:${gid} -R /home/abc

USER abc
ENV HOME /home/abc
WORKDIR $HOME
CMD /bin/bash
```
See: https://stackoverflow.com/questions/36490627/how-to-create-and-run-docker-container-with-new-user-other-than-root

**Comment by GentlemanHal** [comment]
We switched to using a Dockerfile in the main Nevergreen repo as it allowed us to easily publish changes to Docker Hub as part of our CI pipeline.

So basically this repo is deprecated now, but I've updated the Dockerfile in the main Nevergreen repo with this change.

https://github.com/build-canaries/nevergreen/commit/bac3e2d922b6e090ca52de9c69a83060eeeff94f
